#pragma kernel PrepareRendering

#include "../Common.hlsl"

StructuredBuffer<Particle> _ParticleBufferRead;

RWStructuredBuffer<float4> _ParticleRenderingBufferWrite;

[numthreads(128, 1, 1)]
void PrepareRendering(uint3 id : SV_DispatchThreadID)
{
    RETURN_IF_INVALID(id);

    const uint p_id = id.x;

    const Particle p = _ParticleBufferRead[p_id];

    _ParticleRenderingBufferWrite[p_id] = float4(p.position, length(p.velocity));
}