#ifndef _CS_PIC_PICUTILS_HLSL_
#define _CS_PIC_PICUTILS_HLSL_

#define POSITION_EPSILON 1e-4

#define CLAMP_POSITION(POSITION) POSITION = clamp(POSITION, _GridMin + POSITION_EPSILON, _GridMax - POSITION_EPSILON);

#define ENFORCE_BOUNDARY_CONDITION(C_INDEX, VELOCITY) VELOCITY = C_INDEX > 0 ? VELOCITY : 0.0f;


#endif /* _CS_PIC_PICUTILS_HLSL_ */
