#pragma kernel InitParticle

#include "../Common.hlsl"

RWStructuredBuffer<Particle> _ParticleBufferWrite;

[numthreads(128, 1, 1)]
void InitParticle(uint3 id : SV_DispatchThreadID)
{
    RETURN_IF_INVALID(id);

    const uint p_id = id.x;
    
    Particle p = (Particle)0;
    
    p.position = _ParticleInitRangeMin + PCG3_01(p_id) * (_ParticleInitRangeMax - _ParticleInitRangeMin);
    
    CLAMP_POSITION(p.position);

    _ParticleBufferWrite[p_id] = p;
}