#pragma kernel PrepareRendering

#include "../Common.hlsl"

StructuredBuffer<Particle> _ParticleBufferRead;
RWStructuredBuffer<float4> _ParticleRenderingBufferWrite;

[numthreads(128, 1, 1)]
void PrepareRendering(uint3 thread_id : SV_DispatchThreadID)
{
    RETURN_IF_INVALID(thread_id);

    const uint p_id = thread_id.x;

    const Particle p = _ParticleBufferRead[p_id];

    _ParticleRenderingBufferWrite[p.id] = float4(p.position, length(p.velocity));
}